=== luisvv88/l2mobius/game/data/xsd/playerTemplate.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence minOccurs="1" maxOccurs="1">
				<xs:element name="classId" minOccurs="1" maxOccurs="1">
					<xs:simpleType>
						<xs:restriction base="xs:nonNegativeInteger">
							<xs:minInclusive value="0" />
							<xs:maxInclusive value="136" />
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="staticData" minOccurs="1" maxOccurs="1">
					<xs:complexType>
						<xs:sequence maxOccurs="1" minOccurs="1">
							<xs:element type="xs:nonNegativeInteger" name="baseINT" minOccurs="1" maxOccurs="1" />
							<xs:element type="xs:nonNegativeInteger" name="baseSTR" minOccurs="1" maxOccurs="1" />
							<xs:element type="xs:nonNegativeInteger" name="baseCON" minOccurs="1" maxOccurs="1" />
							<xs:element type="xs:nonNegativeInteger" name="baseMEN" minOccurs="1" maxOccurs="1" />
							<xs:element type="xs:nonNegativeInteger" name="baseDEX" minOccurs="1" maxOccurs="1" />
							<xs:element type="xs:nonNegativeInteger" name="baseWIT" minOccurs="1" maxOccurs="1" />
							<xs:element name="creationPoints" minOccurs="1" maxOccurs="1">
								<xs:complexType>
									<xs:sequence maxOccurs="1" minOccurs="0">
										<xs:element name="node" maxOccurs="unbounded" minOccurs="1">
											<xs:complexType>
												<xs:attribute type="xs:integer" name="x" use="required" />
												<xs:attribute type="xs:integer" name="y" use="required" />
												<xs:attribute type="xs:integer" name="z" use="required" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element type="xs:positiveInteger" name="basePAtk" minOccurs="1" maxOccurs="1" />
							<xs:element type="xs:positiveInteger" name="baseCritRate" minOccurs="1" maxOccurs="1" />
							<xs:element name="baseAtkType" minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base="xs:token">
										<xs:enumeration value="FIST" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element type="xs:positiveInteger" name="basePAtkSpd" minOccurs="1" maxOccurs="1" />
							<xs:element name="basePDef" minOccurs="1" maxOccurs="1">
								<xs:complexType>
									<xs:sequence maxOccurs="1" minOccurs="1">
										<xs:element type="xs:positiveInteger" name="chest" minOccurs="1" maxOccurs="1" />
										<xs:element type="xs:positiveInteger" name="legs" minOccurs="1" maxOccurs="1" />
										<xs:element type="xs:positiveInteger" name="head" minOccurs="1" maxOccurs="1" />
										<xs:element type="xs:positiveInteger" name="feet" minOccurs="1" maxOccurs="1" />
										<xs:element type="xs:positiveInteger" name="gloves" minOccurs="1" maxOccurs="1" />
										<xs:element type="xs:positiveInteger" name="underwear" minOccurs="1" maxOccurs="1" />
										<xs:element type="xs:positiveInteger" name="cloak" minOccurs="1" maxOccurs="1" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element type="xs:positiveInteger" name="baseMAtk" minOccurs="1" maxOccurs="1" />
							<xs:element name="baseMDef" minOccurs="1" maxOccurs="1">
								<xs:complexType>
									<xs:sequence maxOccurs="1" minOccurs="1">
										<xs:element type="xs:positiveInteger" name="rear" minOccurs="1" maxOccurs="1" />
										<xs:element type="xs:positiveInteger" name="lear" minOccurs="1" maxOccurs="1" />
										<xs:element type="xs:positiveInteger" name="rfinger" minOccurs="1" maxOccurs="1" />
										<xs:element type="xs:positiveInteger" name="lfinger" minOccurs="1" maxOccurs="1" />
										<xs:element type="xs:positiveInteger" name="neck" minOccurs="1" maxOccurs="1" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element type="xs:nonNegativeInteger" name="baseCanPenetrate" minOccurs="1" maxOccurs="1" />
							<xs:element type="xs:positiveInteger" name="baseAtkRange" minOccurs="1" maxOccurs="1" />
							<xs:element name="baseDamRange" minOccurs="1" maxOccurs="1">
								<xs:complexType>
									<xs:sequence maxOccurs="1" minOccurs="1">
										<xs:element type="xs:nonNegativeInteger" name="verticalDirection" minOccurs="1" maxOccurs="1" />
										<xs:element type="xs:nonNegativeInteger" name="horizontalDirection" minOccurs="1" maxOccurs="1" />
										<xs:element type="xs:nonNegativeInteger" name="distance" minOccurs="1" maxOccurs="1" />
										<xs:element type="xs:nonNegativeInteger" name="width" minOccurs="1" maxOccurs="1" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element type="xs:positiveInteger" name="baseRndDam" minOccurs="1" maxOccurs="1" />
							<xs:element name="baseMoveSpd" minOccurs="1" maxOccurs="1">
								<xs:complexType>
									<xs:sequence maxOccurs="1" minOccurs="1">
										<xs:element type="xs:positiveInteger" name="walk" minOccurs="1" maxOccurs="1" />
										<xs:element type="xs:positiveInteger" name="run" minOccurs="1" maxOccurs="1" />
										<xs:element type="xs:positiveInteger" name="slowSwim" minOccurs="1" maxOccurs="1" />
										<xs:element type="xs:positiveInteger" name="fastSwim" minOccurs="1" maxOccurs="1" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element type="xs:positiveInteger" name="baseBreath" minOccurs="1" maxOccurs="1" />
							<xs:element type="xs:positiveInteger" name="baseSafeFall" minOccurs="1" maxOccurs="1" />
							<xs:element name="collisionMale" minOccurs="1" maxOccurs="1">
								<xs:complexType>
									<xs:sequence maxOccurs="1" minOccurs="1">
										<xs:element type="xs:decimal" name="radius" minOccurs="1" maxOccurs="1" />
										<xs:element type="xs:decimal" name="height" minOccurs="1" maxOccurs="1" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="collisionFemale" minOccurs="1" maxOccurs="1">
								<xs:complexType>
									<xs:sequence maxOccurs="1" minOccurs="1">
										<xs:element type="xs:decimal" name="radius" minOccurs="1" maxOccurs="1" />
										<xs:element type="xs:decimal" name="height" minOccurs="1" maxOccurs="1" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="lvlUpgainData" minOccurs="1" maxOccurs="1">
					<xs:complexType>
						<xs:sequence maxOccurs="1" minOccurs="1">
							<xs:element name="level" maxOccurs="85" minOccurs="85">
								<xs:complexType>
									<xs:sequence maxOccurs="1" minOccurs="1">
										<xs:element type="xs:decimal" name="hp" minOccurs="1" maxOccurs="1" />
										<xs:element type="xs:decimal" name="mp" minOccurs="1" maxOccurs="1" />
										<xs:element type="xs:decimal" name="cp" minOccurs="1" maxOccurs="1" />
										<xs:element type="xs:decimal" name="hpRegen" minOccurs="1" maxOccurs="1" />
										<xs:element type="xs:decimal" name="mpRegen" minOccurs="1" maxOccurs="1" />
										<xs:element type="xs:decimal" name="cpRegen" minOccurs="1" maxOccurs="1" />
									</xs:sequence>
									<xs:attribute name="val" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:positiveInteger">
												<xs:minInclusive value="1" />
												<xs:maxInclusive value="85" />
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== luisvv88/l2mobius/game/data/stats/players/templates/2ndClass/Warlord.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../xsd/playerTemplate.xsd">
	<classId>3</classId>
	<staticData>
		<baseINT>21</baseINT>
		<baseSTR>40</baseSTR>
		<baseCON>43</baseCON>
		<baseMEN>25</baseMEN>
		<baseDEX>30</baseDEX>
		<baseWIT>11</baseWIT>
		<creationPoints>
			<node x="-71338" y="258271" z="-3104" />
			<node x="-71417" y="258270" z="-3104" />
			<node x="-71453" y="258305" z="-3104" />
			<node x="-71467" y="258378" z="-3104" />
		</creationPoints>
		<basePAtk>4</basePAtk>
		<baseCritRate>4</baseCritRate>
		<baseAtkType>FIST</baseAtkType>
		<basePAtkSpd>300</basePAtkSpd>
		<basePDef>
			<chest>31</chest>
			<legs>18</legs>
			<head>12</head>
			<feet>7</feet>
			<gloves>8</gloves>
			<underwear>3</underwear>
			<cloak>1</cloak>
		</basePDef>
		<baseMAtk>6</baseMAtk>
		<baseMDef>
			<rear>9</rear>
			<lear>9</lear>
			<rfinger>5</rfinger>
			<lfinger>5</lfinger>
			<neck>13</neck>
		</baseMDef>
		<baseCanPenetrate>0</baseCanPenetrate>
		<baseAtkRange>20</baseAtkRange>
		<baseDamRange>
			<verticalDirection>0</verticalDirection>
			<horizontalDirection>0</horizontalDirection>
			<distance>26</distance>
			<width>120</width>
		</baseDamRange>
		<baseRndDam>10</baseRndDam>
		<baseMoveSpd>
			<walk>80</walk>
			<run>115</run>
			<slowSwim>50</slowSwim>
			<fastSwim>50</fastSwim>
		</baseMoveSpd>
		<baseBreath>100</baseBreath>
		<baseSafeFall>250</baseSafeFall>
		<collisionMale>
			<radius>9.0</radius>
			<height>23</height>
		</collisionMale>
		<collisionFemale>
			<radius>8.0</radius>
			<height>23.5</height>
		</collisionFemale>
	</staticData>
	<lvlUpgainData>
		<level val="1">
			<hp>80.0</hp>
			<mp>30.0</mp>
			<cp>64.0</cp>
			<hpRegen>2.0</hpRegen>
			<mpRegen>0.9</mpRegen>
			<cpRegen>2.0</cpRegen>
		</level>
		<level val="2">
			<hp>91.83</hp>
			<mp>35.46</mp>
			<cp>73.464</cp>
			<hpRegen>2.05</hpRegen>
			<mpRegen>0.9</mpRegen>
			<cpRegen>2.0</cpRegen>
		</level>
		<level val="3">
			<hp>103.79</hp>
			<mp>40.98</mp>
			<cp>83.032</cp>
			<hpRegen>2.1</hpRegen>
			<mpRegen>0.9</mpRegen>
			<cpRegen>2.0</cpRegen>
		</level>
		<level val="4">
			<hp>115.88</hp>
			<mp>46.56</mp>
			<cp>92.704</cp>
			<hpRegen>2.15</hpRegen>
			<mpRegen>0.9</mpRegen>
			<cpRegen>2.0</cpRegen>
		</level>
		<level val="5">
			<hp>128.1</hp>
			<mp>52.2</mp>
			<cp>102.48</cp>
			<hpRegen>2.2</hpRegen>
			<mpRegen>0.9</mpRegen>
			<cpRegen>2.0</cpRegen>
		</level>
		<level val="6">
			<hp>140.45</hp>
			<mp>57.9</mp>
			<cp>112.36</cp>
			<hpRegen>2.25</hpRegen>
			<mpRegen>0.9</mpRegen>
			<cpRegen>2.0</cpRegen>
		</level>
		<level val="7">
			<hp>152.93</hp>
			<mp>63.66</mp>
			<cp>122.344</cp>
			<hpRegen>2.3</hpRegen>
			<mpRegen>0.9</mpRegen>
			<cpRegen>2.0</cpRegen>
		</level>
		<level val="8">
			<hp>165.54</hp>
			<mp>69.48</mp>
			<cp>132.432</cp>
			<hpRegen>2.35</hpRegen>
			<mpRegen>0.9</mpRegen>
			<cpRegen>2.0</cpRegen>
		</level>
		<level val="9">
			<hp>178.28</hp>
			<mp>75.36</mp>
			<cp>142.624</cp>
			<hpRegen>2.4</hpRegen>
			<mpRegen>0.9</mpRegen>
			<cpRegen>2.0</cpRegen>
		</level>
		<level val="10">
			<hp>191.15</hp>
			<mp>81.3</mp>
			<cp>152.92</cp>
			<hpRegen>2.45</hpRegen>
			<mpRegen>0.9</mpRegen>
			<cpRegen>2.0</cpRegen>
		</level>
		<level val="11">
			<hp>204.15</hp>
			<mp>87.3</mp>
			<cp>163.32</cp>
			<hpRegen>2.5</hpRegen>
			<mpRegen>1.2</mpRegen>
			<cpRegen>2.5</cpRegen>
		</level>
		<level val="12">
			<hp>217.28</hp>
			<mp>93.36</mp>
			<cp>173.824</cp>
			<hpRegen>2.6</hpRegen>
			<mpRegen>1.2</mpRegen>
			<cpRegen>2.5</cpRegen>
		</level>
		<level val="13">
			<hp>230.54</hp>
			<mp>99.48</mp>
			<cp>184.432</cp>
			<hpRegen>2.7</hpRegen>
			<mpRegen>1.2</mpRegen>
			<cpRegen>2.5</cpRegen>
		</level>
		<level val="14">
			<hp>243.93</hp>
			<mp>105.66</mp>
			<cp>195.144</cp>
			<hpRegen>2.8</hpRegen>
			<mpRegen>1.2</mpRegen>
			<cpRegen>2.5</cpRegen>
		</level>
		<level val="15">
			<hp>257.45</hp>
			<mp>111.9</mp>
			<cp>205.96</cp>
			<hpRegen>2.9</hpRegen>
			<mpRegen>1.2</mpRegen>
			<cpRegen>2.5</cpRegen>
		</level>
		<level val="16">
			<hp>271.1</hp>
			<mp>118.2</mp>
			<cp>216.88</cp>
			<hpRegen>3.0</hpRegen>
			<mpRegen>1.2</mpRegen>
			<cpRegen>2.5</cpRegen>
		</level>
		<level val="17">
			<hp>284.88</hp>
			<mp>124.56</mp>
			<cp>227.904</cp>
			<hpRegen>3.1</hpRegen>
			<mpRegen>1.2</mpRegen>
			<cpRegen>2.5</cpRegen>
		</level>
		<level val="18">
			<hp>298.79</hp>
			<mp>130.98</mp>
			<cp>239.032</cp>
			<hpRegen>3.2</hpRegen>
			<mpRegen>1.2</mpRegen>
			<cpRegen>2.5</cpRegen>
		</level>
		<level val="19">
			<hp>312.83</hp>
			<mp>137.46</mp>
			<cp>250.264</cp>
			<hpRegen>3.3</hpRegen>
			<mpRegen>1.2</mpRegen>
			<cpRegen>2.5</cpRegen>
		</level>
		<level val="20">
			<hp>327.0</hp>
			<mp>144.0</mp>
			<cp>261.6</cp>
			<hpRegen>3.4</hpRegen>
			<mpRegen>1.2</mpRegen>
			<cpRegen>2.5</cpRegen>
		</level>
		<level val="21">
			<hp>360.0</hp>
			<mp>153.9</mp>
			<cp>288.0</cp>
			<hpRegen>3.5</hpRegen>
			<mpRegen>1.5</mpRegen>
			<cpRegen>3.5</cpRegen>
		</level>
		<level val="22">
			<hp>393.3</hp>
			<mp>163.89</mp>
			<cp>314.64</cp>
			<hpRegen>3.6</hpRegen>
			<mpRegen>1.5</mpRegen>
			<cpRegen>3.5</cpRegen>
		</level>
		<level val="23">
			<hp>426.9</hp>
			<mp>173.97</mp>
			<cp>341.52</cp>
			<hpRegen>3.7</hpRegen>
			<mpRegen>1.5</mpRegen>
			<cpRegen>3.5</cpRegen>
		</level>
		<level val="24">
			<hp>460.8</hp>
			<mp>184.14</mp>
			<cp>368.64</cp>
			<hpRegen>3.8</hpRegen>
			<mpRegen>1.5</mpRegen>
			<cpRegen>3.5</cpRegen>
		</level>
		<level val="25">
			<hp>495.0</hp>
			<mp>194.4</mp>
			<cp>396.0</cp>
			<hpRegen>3.9</hpRegen>
			<mpRegen>1.5</mpRegen>
			<cpRegen>3.5</cpRegen>
		</level>
		<level val="26">
			<hp>529.5</hp>
			<mp>204.75</mp>
			<cp>423.6</cp>
			<hpRegen>4.0</hpRegen>
			<mpRegen>1.5</mpRegen>
			<cpRegen>3.5</cpRegen>
		</level>
		<level val="27">
			<hp>564.3</hp>
			<mp>215.19</mp>
			<cp>451.44</cp>
			<hpRegen>4.1</hpRegen>
			<mpRegen>1.5</mpRegen>
			<cpRegen>3.5</cpRegen>
		</level>
		<level val="28">
			<hp>599.4</hp>
			<mp>225.72</mp>
			<cp>479.52</cp>
			<hpRegen>4.2</hpRegen>
			<mpRegen>1.5</mpRegen>
			<cpRegen>3.5</cpRegen>
		</level>
		<level val="29">
			<hp>634.8</hp>
			<mp>236.34</mp>
			<cp>507.84</cp>
			<hpRegen>4.3</hpRegen>
			<mpRegen>1.5</mpRegen>
			<cpRegen>3.5</cpRegen>
		</level>
		<level val="30">
			<hp>670.5</hp>
			<mp>247.05</mp>
			<cp>536.4</cp>
			<hpRegen>4.4</hpRegen>
			<mpRegen>1.5</mpRegen>
			<cpRegen>3.5</cpRegen>
		</level>
		<level val="31">
			<hp>706.5</hp>
			<mp>257.85</mp>
			<cp>565.2</cp>
			<hpRegen>4.5</hpRegen>
			<mpRegen>1.8</mpRegen>
			<cpRegen>4.5</cpRegen>
		</level>
		<level val="32">
			<hp>742.8</hp>
			<mp>268.74</mp>
			<cp>594.24</cp>
			<hpRegen>4.6</hpRegen>
			<mpRegen>1.8</mpRegen>
			<cpRegen>4.5</cpRegen>
		</level>
		<level val="33">
			<hp>779.4</hp>
			<mp>279.72</mp>
			<cp>623.52</cp>
			<hpRegen>4.7</hpRegen>
			<mpRegen>1.8</mpRegen>
			<cpRegen>4.5</cpRegen>
		</level>
		<level val="34">
			<hp>816.3</hp>
			<mp>290.79</mp>
			<cp>653.04</cp>
			<hpRegen>4.8</hpRegen>
			<mpRegen>1.8</mpRegen>
			<cpRegen>4.5</cpRegen>
		</level>
		<level val="35">
			<hp>853.5</hp>
			<mp>301.95</mp>
			<cp>682.8</cp>
			<hpRegen>4.9</hpRegen>
			<mpRegen>1.8</mpRegen>
			<cpRegen>4.5</cpRegen>
		</level>
		<level val="36">
			<hp>891.0</hp>
			<mp>313.2</mp>
			<cp>712.8</cp>
			<hpRegen>5.0</hpRegen>
			<mpRegen>1.8</mpRegen>
			<cpRegen>4.5</cpRegen>
		</level>
		<level val="37">
			<hp>928.8</hp>
			<mp>324.54</mp>
			<cp>743.04</cp>
			<hpRegen>5.1</hpRegen>
			<mpRegen>1.8</mpRegen>
			<cpRegen>4.5</cpRegen>
		</level>
		<level val="38">
			<hp>966.9</hp>
			<mp>335.97</mp>
			<cp>773.52</cp>
			<hpRegen>5.2</hpRegen>
			<mpRegen>1.8</mpRegen>
			<cpRegen>4.5</cpRegen>
		</level>
		<level val="39">
			<hp>1005.3</hp>
			<mp>347.49</mp>
			<cp>804.24</cp>
			<hpRegen>5.3</hpRegen>
			<mpRegen>1.8</mpRegen>
			<cpRegen>4.5</cpRegen>
		</level>
		<level val="40">
			<hp>1044.0</hp>
			<mp>359.1</mp>
			<cp>835.2</cp>
			<hpRegen>5.4</hpRegen>
			<mpRegen>1.8</mpRegen>
			<cpRegen>4.5</cpRegen>
		</level>
		<level val="41">
			<hp>1098.6</hp>
			<mp>378.6</mp>
			<cp>878.88</cp>
			<hpRegen>5.5</hpRegen>
			<mpRegen>2.1</mpRegen>
			<cpRegen>5.5</cpRegen>
		</level>
		<level val="42">
			<hp>1153.62</hp>
			<mp>398.25</mp>
			<cp>922.896</cp>
			<hpRegen>5.6</hpRegen>
			<mpRegen>2.1</mpRegen>
			<cpRegen>5.5</cpRegen>
		</level>
		<level val="43">
			<hp>1209.06</hp>
			<mp>418.05</mp>
			<cp>967.248</cp>
			<hpRegen>5.7</hpRegen>
			<mpRegen>2.1</mpRegen>
			<cpRegen>5.5</cpRegen>
		</level>
		<level val="44">
			<hp>1264.92</hp>
			<mp>438.0</mp>
			<cp>1011.936</cp>
			<hpRegen>5.8</hpRegen>
			<mpRegen>2.1</mpRegen>
			<cpRegen>5.5</cpRegen>
		</level>
		<level val="45">
			<hp>1321.2</hp>
			<mp>458.1</mp>
			<cp>1056.96</cp>
			<hpRegen>5.9</hpRegen>
			<mpRegen>2.1</mpRegen>
			<cpRegen>5.5</cpRegen>
		</level>
		<level val="46">
			<hp>1377.9</hp>
			<mp>478.35</mp>
			<cp>1102.32</cp>
			<hpRegen>6.0</hpRegen>
			<mpRegen>2.1</mpRegen>
			<cpRegen>5.5</cpRegen>
		</level>
		<level val="47">
			<hp>1435.02</hp>
			<mp>498.75</mp>
			<cp>1148.016</cp>
			<hpRegen>6.1</hpRegen>
			<mpRegen>2.1</mpRegen>
			<cpRegen>5.5</cpRegen>
		</level>
		<level val="48">
			<hp>1492.56</hp>
			<mp>519.3</mp>
			<cp>1194.048</cp>
			<hpRegen>6.2</hpRegen>
			<mpRegen>2.1</mpRegen>
			<cpRegen>5.5</cpRegen>
		</level>
		<level val="49">
			<hp>1550.52</hp>
			<mp>540.0</mp>
			<cp>1240.416</cp>
			<hpRegen>6.3</hpRegen>
			<mpRegen>2.1</mpRegen>
			<cpRegen>5.5</cpRegen>
		</level>
		<level val="50">
			<hp>1608.9</hp>
			<mp>560.85</mp>
			<cp>1287.12</cp>
			<hpRegen>6.4</hpRegen>
			<mpRegen>2.1</mpRegen>
			<cpRegen>5.5</cpRegen>
		</level>
		<level val="51">
			<hp>1667.7</hp>
			<mp>581.85</mp>
			<cp>1334.16</cp>
